### PR TITLE
Add a Java 9 matrix build to AppVeyor

### PR DESCRIPTION
**Pull request by sschuberth**
@sksamuel, please let the CI builds finish before merging to double-check this really works.

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by sksamuel** [comment]
After this works check out 3.10-RC1 if you like, I've added loads of new features.

**Comment by sschuberth** [comment]
Please do not merge yet, I'm not confident this does the right thing despite being green. Will investigate later.

**Comment by sschuberth** [comment]
@sksamuel, I believe this is good to merge now.

**Pull request merged**
