### PR TITLE
Fix function name in property docs examples

### PR DESCRIPTION
**Pull request by dhoepelman**
Property-based testing docs should use `assertAll`

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by Kerooker** [comment]
Hey, @sksamuel 
```
forAll(Gen.string()) {
...
}
```

Is also a valid call. Is it actually better to use `assertAll`?

**Comment by Kerooker** [comment]
Maybe we should improve the documentation to say that forAll and assertAll are different in that sense?

**Comment by sksamuel** [comment]
That would be better.

**Comment by dhoepelman** [comment]
> Maybe we should improve the documentation to say that forAll and assertAll are different in that sense?

Would be a good addition! My confusion was caused by multiple `forAll` operators existing, causing me to import the incorrect one, and `forAll` not being mentioned previously in the property-drive testing docs.

**Pull request merged**
