### PR TITLE
Moves all assertions tests to the assertions module

### PR DESCRIPTION
**Pull request by Kerooker**
As part of https://github.com/kotlintest/kotlintest/issues/498, all tests that test the `kotlintest-assertions` module were moved to it, bringing the tests closer to their targets, and decreasing confusion to future contributors.

An important point to be noted: the root package chosen is `assertions.io.kotlintest`. This was done because putting files in `io.kotlintest` package make them subject to stacktrace cleaning, by the Failures class. The Failures class removes all Kotlintest stacktraces from throwables, so that the user only sees the real problem, and nothing internal. However. as we're using `io.kotlintest` for all the tests, the user stacktraces would be removed (we are the users), and that's not good when a test fails, as no reason would be given.

Fixes a part of #498 - Moves tests closer to their targets

### CODE REVIEW

**Comment by Kerooker** [comment]
@sksamuel 
Could you tell appveyor to rerun tests, please?

**Comment by sksamuel** [comment]
> @sksamuel
> Could you tell appveyor to rerun tests, please?

Yep

**Comment by sksamuel** [comment]
> An important point to be noted: the root package chosen is `assertions.io.kotlintest`. This was done because putting files in `io.kotlintest` package make them subject to stacktrace cleaning, by the Failures class. The Failures class removes all Kotlintest stacktraces from throwables, so that the user only sees the real problem, and nothing internal. However. as we're using `io.kotlintest` for all the tests, the user stacktraces would be removed (we are the users), and that's not good when a test fails, as no reason would be given.

That's why I use com.sksamuel for tests in kotlintest core :)
I don't want to use 'kotlintest' anywhere in the package name to totally remove anything like this.

**Comment by Kerooker** [comment]
Should e use com.sksamuel? Maybe io.kt?

**Comment by sksamuel** [comment]
I own com.sksamuel io.kotlintest, anything else is fake.
But up to you.

**Comment by Kerooker** [comment]
com.sksamuel it is then

**Comment by sksamuel** [comment]
Looks good when green.

**Comment by Kerooker** [comment]
Should be ok with last commit

**Pull request merged**
