### PR TITLE
fixed that Gen.oneOf would not choose the last element and added a test for it.

### PR DESCRIPTION
**Pull request by reckter**
(if someone knows how to update my fork without creating a pull request every time, I would be flattered!)

### CODE REVIEW

**Comment by reckter** [comment]
Maybee a release of this should be considered, as of right now the release version is broken. (it only ever chooses the first element of the given list)

**Comment by sksamuel** [comment]
Create a remote back to the original repo, and then you can fetch that, `git fetch original` and then you can merge that into your fork master, `git checkout master; git merge original/master`

**Comment by helmbold** [comment]
Could this be closed?

**Comment by sksamuel** [comment]
It's a PR, its already closed :)

**Pull request merged**
