### PR TITLE
FileMatchersTest: Fix handling Windows paths

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sksamuel** [comment]
Ah yes, thanks!
I always forget to boot into windows to check these things.

**Comment by sschuberth** [comment]
Did you think about using AppVeyor CI for Windows tests?

**Comment by sksamuel** [comment]
What's that. Like a travis but for windows?

**Comment by sschuberth** [comment]
Yes: https://www.appveyor.com/

**Comment by sksamuel** [comment]
https://ci.appveyor.com/project/sksamuel/kotlintest

**Comment by sksamuel** [comment]
If you know this platform do you want to Pr for a configuration file? Or I can learn it if you don't.

**Comment by sschuberth** [comment]
Done: https://github.com/kotlintest/kotlintest/pull/284

**Pull request merged**
