### PR TITLE
Kotlin version upgrade

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sksamuel** [comment]
AppVeyor doesn't like it for some reason.

**Comment by sschuberth** [comment]
Looks like a temporary network hiccup, I can reach the URL in question from my Windows machine. Anyway, let me use the chance to also bump the Gradle version and retrigger the builds.

**Comment by sksamuel** [comment]
Ok

**Comment by sksamuel** [comment]
I had to downgrade gradle the other week due to errors in travis.

**Comment by sschuberth** [comment]
Looks like I managed to fix the issue 😉

**Comment by sksamuel** [comment]
Better man than me :)

**Pull request merged**
