### PR TITLE
Add Gradle wrapper to the project

### PR DESCRIPTION
**Pull request by MichaelRocks**

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by russel** [comment]
There doesn't appear to be a wrapper task in the build.gradle so as to manage upgrade of the wrapper.

**Comment by MichaelRocks** [comment]
@russel You don't need a wrapper task in the build.grade for that. It can be done from CLI:
```
./gradlew wrapper --gradle-version <version>
```

**Comment by russel** [comment]
@MichaelRocks Shows how poorly I have kept up with gradle CLI changes…sorry for the noise.

**Pull request merged**
