### PR TITLE
Add documentation to Date matchers

### PR DESCRIPTION
**Pull request by Kerooker**
Currently a work in progress, don't merge yet.

This PR is for code review to be made while changes happen, as they can happen individually.

### CODE REVIEW

**Comment by Kerooker** [comment]
I recommend viewing commit by commit while reviewing the docs

**Comment by Kerooker** [comment]
@ajalt 
First things first: thanks for the review and the comment!

But for me, Intellij resolves Dokka correctly. What might be going on?
image

**Comment by ajalt** [comment]
The screenshot I posted was from another project that I added the dependency to. I don't believe that the samples are included in sources jars, but please correct me if I'm wrong.

**Comment by Kerooker** [comment]
Understood. Should I include the samples in the jar or is it better to just do what you said and add samples to the docs (not referencing at all)?

**Comment by ajalt** [comment]
If I was writing it, I would add the samples to the docs, but if you can get the samples to resolve in the jar, that would work, too. I'll let @sksamuel weigh in if he prefers one over the other.

**Comment by sksamuel** [comment]
I have no preference either way.

**Comment by Kerooker** [comment]
Then to avoid having troubles with a bigger jar (not that bigger, but bigger anyways) and maintainability of the code (people might forget to update the samples when they update the code), I'll refactor the samples to be in-docs

**Comment by Kerooker** [comment]
@ajalt Please review this again and see if this matches what we talked about.

**Comment by Kerooker** [comment]
Don't merge just yet. There are still some docs in this file to handle. I should finish soon

**Comment by Kerooker** [comment]
@ajalt and @sksamuel 
I believe it's all done.

Please review one more time before mergind. There was a lot of copy pasting stuff, and I might have forgotten to replace an instance or two. I don't believe it happened, but just to be sure..

**Pull request closed without merging**
