### PR TITLE
Matcher support for any objects inheriting `Comparable<T>`

### PR DESCRIPTION
**Pull request by hhandoko**
Added support for matchers comparing two objects inheriting `Comparable<T>`.

Test conditions reads closer to natural language, e.g. `value1 should be gt value2` as opposed to `(value1 > value2) shouldBe true`.

### CODE REVIEW

**Comment by helmbold** [comment]
Thanks for your contribution. I think we should merge this to 1.3 and/or 2.0 branch. What do you think @sksamuel ?

**Comment by sksamuel** [comment]
2.0 i think

**Comment by helmbold** [comment]
@hhandoko I've changed the target to 2.0. It would be great if you would resolve the remaining conflicts.

**Comment by hhandoko** [comment]
Thanks @sksamuel . I'll have a look at the `2.0` branch and review the conflicts.

**Comment by hhandoko** [comment]
@sksamuel @helmbold I've decided to port over the changes for version 2 and created a new PR - #126. I'll close this PR.

I think it's cleaner and easier to avoid accidental changes via rebase / merge, since `release/2.0` has diverged quite far from last `master` commit.

Please review when you have the chance, thanks

**Pull request closed without merging**
