### PR TITLE
Updated Kotlin to stable version 1.1.1 removing unneeded eap reposito…

### PR DESCRIPTION
**Pull request by jrgonzalezg**
…ries. Also removed unneeded sourceSets declaration.

Using kotlintest is requiring to use eap repositories which should not be needed now that Kotlin 1.1 is stable. Could you generate a new version of kotlintest with this so it can be used without issues in Kotlin 1.1 projects?

### CODE REVIEW

**Comment by sksamuel** [comment]
Can you PR this against the 2.0 branch please.

**Comment by jrgonzalezg** [comment]
Done on #166 although there the eap repositories where already gone so that was not needed. Does this mean that the 2.0 branch is going to produce a release soon? If not, i still think it would be good to release a 1.x version with Kotlin 1.1.1

**Comment by sksamuel** [comment]
2.0 will be released this weekend.

**Comment by jrgonzalezg** [comment]
Great!

**Pull request closed without merging**
