### PR TITLE
[Minor] Documentation Update 

### PR DESCRIPTION
**Pull request by gokulchandra**
Minor change to docs to reflect the updated versions of the dependency across documentation.

### CODE REVIEW

**Comment by gokulchandra** [comment]
@Kerooker 	I don't think I have access to CI logs. Any idea why the build is failing?

**Comment by sksamuel** [comment]
It's a problem with the main build not your change.

**Comment by Kerooker** [comment]
@gokulchandra Something a few commits ago broke Trevis, and it now takes forever (literally) for a test to go through. Don't worry about it, we're working on a fix already

**Comment by gokulchandra** [comment]
> @gokulchandra Something a few commits ago broke Trevis, and it now takes forever (literally) for a test to go through. Don't worry about it, we're working on a fix already

Sounds great. Thanks for explaining that.

**Comment by Kerooker** [comment]
If you want to follow this problem with CI, take a look at https://github.com/kotlintest/kotlintest/issues/457.

I'll execute tests with your branch and merge your PR if they're successful.

**Comment by Kerooker** [comment]
If you want to follow this problem with CI, take a look at https://github.com/kotlintest/kotlintest/issues/457.

I'll execute tests with your branch and merge your PR if they're successful.

**Comment by sksamuel** [comment]
:+1:

**Pull request merged**
